In [2]:
import numpy as np

x=[10,20,30,40,50]
myarr = np.array(x)
myarr

array([10, 20, 30, 40, 50])

In [3]:
import numpy as np

myarr = np.array([10,20,30,40,50])
myarr

array([10, 20, 30, 40, 50])

In [6]:
import numpy as np

my_list = []
n = int(input("Enter how many elements you want in array : "))
for i in range(n):
    val = int(input('enter value : '))
    my_list.append(val)

my_array = np.array(my_list)
my_array


Enter how many elements you want in array :  5
enter value :  1
enter value :  2
enter value :  3
enter value :  4
enter value :  5


array([1, 2, 3, 4, 5])